spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      data-locations: classpath:data.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정
      schema-locations: classpath:data.sql # 서버 시작시 ddl sql문을 실행할 위치 및 파일 지정
  ### AWS 관리 ###
  profiles:
    include: aws

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true