spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: oauth
---
spring:
  config:
    activate:
      on-profile: server
  h2:
    console:
      enabled: true
      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
  datasource:
    url: jdbc:mysql://codestates-seb39-054.cgo4ftt0wnjw.ap-northeast-2.rds.amazonaws.com:3306/DB_MainProject_054?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: Qordpsem1!

  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    open-in-view: false


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true
