spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
spring:
  config:
#    location: classpath:aws.yml
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true

cloud:
  aws:
    credentials:
      accessKey: AKIA2WL4MMEVN5YNHOQS
      secretKey: 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
    s3:
      bucket: mainproject54
      dir: /productImage
    region:
      static: ap-northeast-2
    stack:
      auto: false